config/routes.rb
Rails.application.routes.draw do
  devise_for :authors

  # Defines the root path route ("/")
  root "authors#index"
  resources :authors do
    resources :posts do
      resources :comments
      resources :likes, only: [:create, :destroy]
    end
  end

   # API ROUTES
  namespace :api do # /api
    namespace :v1 do # /api/v1
      resources :authors do # api/v1/users
        resources :posts, format: :json do # api/v1/users/:user_id/posts
          resources :comments, format: :json # api/v1/users/:user_id/posts/:post_id/comments
        end
      end
    end
  end
  post "/login", to: "authors#login"
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  after_save :update_comments_counter

  belongs_to :author
  belongs_to :post

  private

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::V1::ApplicationController
  def create
    post = Post.find_by(id: params[:post_id])
    author = Author.find_by(id: params[:author_id])
    comment = Comment.new(
      text: params[:comment][:text],
      post_id: post.id,
      author_id: author.id
    )
    if comment.save
      render json: comment, status: :created
    else
      render json: comment.errors, status: :unprocessable_entity
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find_by(id: params[:post_id])
    @comment = Comment.new(
      text: params[:comment][:text],
      post_id: @post.id,
      author_id: current_author.id
    )
    if @comment.save
      redirect_back_or_to author_post_path(current_author, @post)
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id]).destroy
    @post = Post.find_by(id: params[:post_id])
    respond_to do |format|
      format.html do
        redirect_back_or_to author_post_path(current_author, @post), notice: 'Comment was successfully deleted.'
      end
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <img src="https://picsum.photos/200" />
  <div class="author-comment">
    <h4><%= comment.author.name %></h4>
    <p><%= comment.text %></p>
  </div>
  <% if can? :destroy, comment %>
    <%= form_with model: comment, url: author_post_comment_path(comment.author, comment.post, comment), method: :delete do |form| %>
      <%= form.submit "Delete", class: "btn" %>
    <% end %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [ @post.author, @post, @post.comments.build ], class: 'comment-form' do |form| %>
  <%= form.label :text %>
  <%= form.text_field :text, class: 'comment-input', placeholder: "Write a comment..." %>
  <%= form.submit "Comment", class: 'btn' %>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1><br>

<%= form_with model: @comment, url: author_post_comments_path, method: :post do |form| %>
  <%= form.label :text %>
  <%= form.text_field :text %><br><br>
  <%= form.submit "Submit" %>

  <% if @comment.errors.any? %>
    <% @comment.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  <% end %>
<% end %>