config/routes.rb
Rails.application.routes.draw do
  devise_for :authors

  # Defines the root path route ("/")
  root "authors#index"
  resources :authors do
    resources :posts do
      resources :comments
      resources :likes, only: [:create, :destroy]
    end
  end

   # API ROUTES
  namespace :api do # /api
    namespace :v1 do # /api/v1
      resources :authors do # api/v1/users
        resources :posts, format: :json do # api/v1/users/:user_id/posts
          resources :comments, format: :json # api/v1/users/:user_id/posts/:post_id/comments
        end
      end
    end
  end
  post "/login", to: "authors#login"
  
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :posts, dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, comparison: { greater_than_or_equal_to: 0 }, numericality: { only_integer: true }

  def three_recent_posts
    posts.includes(%i[likes comments]).order('created_at DESC').first(3)
  end
end

app/controllers/api/v1/authors_controller.rb
class Api::V1::AuthorsController < Api::V1::ApplicationController
  def index
    authors = Author.all
    render json: authors
  end

  def show
    author = Author.find(params[:id])
    render json: author
  end

  # def create
  #   @author = Author.create(author_params)
  #   if @author.valid?
  #     token = encode_token({ author_id: @author.id })
  #     render json: { author: @author, token: token }, status: :ok
  #   else
  #     render json: { error: "Invalid name or password" }, status: :unprocessable_entity
  #   end
  # end

  # def login
  #   @author = Author.find_by(name: params[:name])
  #   if @author && @author.autenticate(author_params[:password])
  #     token = encode_token({ author_id: @author.id })
  #     render json: { author: @author, token: token }, status: :ok
  #   else
  #     render json: { error: "Invalid name or password" }, status: :unprocessable_entity
  #   end
  # end

  # private

  # def author_params
  #   params.require(:author).permit(:name, :password)
  # end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/index.html.erb
<div class="author-list">
  <% @authors.includes([:posts]).each do |author| %>
    
      <div class="author-card">    
        <img src="https://picsum.photos/200" />
        <div class = "author-details">
        <%= link_to author_path(author), class: 'author-link' do %>
          <h2><%= author.name %></h2>
          <% end %>
          <p>Number of posts: <%= author.posts.length %></p>
        </div>
      </div>
    
  <% end %>
</div>

app/views/authors/show.html.erb
<div class="author-show">

  <div class="author-data">
    <img src='https://picsum.photos/200' />
    <div class="portrait"></div>
    <div class="name-post">
      <h2><%= @author.name %></h2>
      <p>Posts: <%= @author.posts.length %></p>
    </div>
    <div class="author-bio">
      <h4>Bio</h4>
      <p> <%= @author.bio %> </p>
    </div>
  </div>
  
  <div class="author-recent-posts">
    <%= render "posts/form" %>
    <h3 class="recent-posts-title">Three most recent posts:</h3>
    <% @author.three_recent_posts.each do |post| %>
      <%= link_to author_post_path(@author, post) do %>
      <div class="post-card">
        <h3><%= post.title %></h3>
        <p><%= post.text %></p>
        <div class="likes-comments">
          <p><%= post.likes.length %> Likes</p>
          <p><%= post.comments.length %> Comments</p>
        </div> 
      </div>
      <% end %>
      <% if can? :destroy, post %>
        <%= form_with model: post, url: author_post_path(@author, post), method: :delete do |form| %>
          <%= form.submit "Delete", class: "btn" %>
        <% end %>
      <% end %>
    <% end %>

    <%= link_to '<button type="button">See All Posts</button>'.html_safe, author_posts_path(@author) %>
    <%#= link_to '<button type="button">New Post</button>'.html_safe, new_author_post_path(@author) %>

    
  </div>

  

</div>